import streamlit as st
import tempfile
import time

from src.feature_extractor import FeatureExtractor
from src.search import ImageSearcher
from src.metadata import MetadataManager


st.set_page_config(
    page_title="Amazon Visual Product Search",
    layout="wide"
)


@st.cache_resource
def load_resources():

    extractor = FeatureExtractor()

    searcher = ImageSearcher()

    metadata = MetadataManager()

    return extractor, searcher, metadata


extractor, searcher, metadata = load_resources()


# ---------------- Sidebar ----------------

st.sidebar.title("Project Details")

st.sidebar.info(
    """
    Model: ResNet50

    Embedding Size: 2048

    Similarity Search:
    KNN + Cosine Distance

    Dataset:
    Myntra Fashion Dataset

    Images Indexed:
    600+
    """
)

# ---------------- Main UI ----------------

st.title("🛍️ AI-Powered Visual Product Search Engine")

st.markdown("""
Upload a fashion product image and retrieve visually similar products using deep learning image embeddings generated by ResNet50.
""")

uploaded_file = st.file_uploader(
    "Upload Product Image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file:

    uploaded_bytes = uploaded_file.getvalue()

    temp_file = tempfile.NamedTemporaryFile(
        delete=False,
        suffix=".jpg"
    )

    temp_file.write(uploaded_bytes)
    temp_file.flush()
    temp_file.close()

    image_path = temp_file.name

    st.subheader("Query Image")

    st.image(
        uploaded_bytes,
        width=250
    )

    try:

        feature = extractor.extract(image_path)

    except Exception as e:

        st.error(f"Feature extraction failed: {e}")
        st.stop()

    start_time = time.time()

    results = searcher.search(feature)

    end_time = time.time()

    search_time = round(
        end_time - start_time,
        3
    )

    st.success(
        f"Retrieved results in {search_time} seconds"
    )

    st.subheader("Similar Products")

    cols = st.columns(5)

    for i, result in enumerate(results[:5]):

        path = result["path"]

        score = result["score"]

        info = metadata.get_product_info(path)

        with cols[i]:

            try:

                st.image(
                    path,
                    width="stretch"
                )

                # st.write(info)

            except Exception:

                st.warning("Image missing")
                continue

            st.metric(
                "Similarity",
                f"{score:.2f}%"

            )

            if info:

                st.markdown(
                    f"**{info['article_type']}**"
                )

                st.caption(
                    f"Color: {info['color']}"
                )

                st.caption(
                    f"Gender: {info['gender']}"
                )

                st.caption(
                    f"Season: {info['season']}"
                )

    st.divider()

    st.subheader("System Statistics")

    col1, col2, col3 = st.columns(3)

    col1.metric(
        "Images Indexed",
        len(searcher.filenames)
    )

    col2.metric(
        "Embedding Size",
        "2048"
    )

    col3.metric(
        "Model",
        "ResNet50"
    )
st.divider()

st.markdown(
    """
    Built using PyTorch, ResNet50, Streamlit, and K-Nearest Neighbors.
    """
)